# Generated by Django 5.2 on 2025-04-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('quantidade_estoque', models.IntegerField()),
                ('image', models.ImageField(default=None, null=True, upload_to='assets/image/%M/%d')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meteora_site.categoria')),
            ],
        ),
    ]
